[build]
builder = "DOCKERFILE"
dockerfilePath = "ui/Dockerfile"
buildPath = "ui"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300

[deploy.env]
PORT = "80"
VITE_API_URL = "https://hackathon-api-production-d702.up.railway.app" 