[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.ui"

[deploy]
startCommand = "sh -c 'nginx -t && nginx -g \"daemon off;\"'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 120
healthcheckInterval = 15

[deploy.env]
PORT = "80"
NGINX_PORT = "80"
VITE_API_URL = "https://hackathon-api-production-d702.up.railway.app" 